"""
PR body assembly.

`render_pr_body(diagnosis, fix_proposal)` is a pure function returning the
markdown body the fixer would post to GitHub. The CLI entry loads an experiment
from the store and renders against its diagnosis + fix proposal.
"""

from __future__ import annotations

from pathlib import Path

import typer

from shared.contracts import DiagnosisReport, FixProposal

CONFIDENCE_LABELS = {  # bucket -> human label
    "high": (0.8, 1.01),
    "med": (0.5, 0.8),
    "low": (0.0, 0.5),
}


def confidence_bucket(confidence: float) -> str:
    """Return 'low' / 'med' / 'high'. Used for PR labels."""
    for label, (lo, hi) in CONFIDENCE_LABELS.items():
        if lo <= confidence < hi:
            return label
    return "low"


def render_pr_body(diagnosis: DiagnosisReport, fix: FixProposal) -> str:
    """Render the markdown PR body. See agents/fixer/README.md for the template."""
    top = diagnosis.hypotheses[0]
    files = "\n".join(f"- `{p}`" for p in fix.files_touched) or "_(no files touched)_"
    evidence_lines = [f"- {e}" for e in top.evidence] or ["_(no evidence cited)_"]
    evidence = "\n".join(evidence_lines)
    test_note = (
        "`<see PR diff>` — fails without this PR, passes with it."
        if fix.regression_test_added
        else "_No regression test added. See reviewer checklist._"
    )

    return f"""## Auto-proposal from chaos experiment {fix.experiment_id}

**Confidence:** {fix.confidence:.2f} ({confidence_bucket(fix.confidence)})
**Fix class:** `{top.suggested_fix_class}`
**Action:** `{fix.action.value}`
**Diagnosis:** {top.summary}

### What this PR changes
{files}

### Why
{evidence}

### Reasoning
{fix.reasoning}

### Regression test
{test_note}

### Reviewer checklist
- [ ] Is the fix correct, or is the diagnosis wrong?
- [ ] Is the regression test the right shape (fails without the patch)?
- [ ] Should we also update docs / runbooks?
- [ ] Are there other places in the codebase with the same pattern?

### Experiment record
- Experiment ID: `{fix.experiment_id}`
- Diagnosis run ID: `{diagnosis.run_id}`
- Fix proposal run ID: `{fix.run_id}`

---
Generated by `chaos`. **Draft — do not merge without review.**
"""


# ---------- CLI ----------------------------------------------------------------

app = typer.Typer(help="Render the PR body for an experiment.", no_args_is_help=False)


@app.callback(invoke_without_command=True)
def main(
    experiment_id: str = typer.Option(..., "--experiment-id"),
    db: Path | None = typer.Option(None, "--db"),
) -> None:
    """Load an experiment from the store and print its PR body to stdout."""
    from orchestrator.store import ExperimentStore

    db_path = db or (Path.home() / ".local" / "share" / "chaos" / "experiments.sqlite")
    store = ExperimentStore(db_path)
    record = store.load(experiment_id)
    if record is None:
        typer.echo(f"no experiment {experiment_id} in store", err=True)
        raise typer.Exit(1)
    if record.diagnosis is None or record.fix_proposal is None:
        typer.echo(
            f"experiment {experiment_id} has no diagnosis or fix_proposal yet", err=True
        )
        raise typer.Exit(1)
    typer.echo(render_pr_body(record.diagnosis, record.fix_proposal))


if __name__ == "__main__":
    app()
